name: npm
description: Installs npm dependencies
inputs:
  immutable:
    description: Abort with an error exit code if the lockfile was to be modified
    default: true
runs:
  using: composite
  steps:
    - name: Install npm dependencies
      if: ${{ inputs.immutable == 'true' }}
      run: npm ci
      shell: bash
    - name: Install npm dependencies (ignore lockfile changes)
      if: ${{ inputs.immutable != 'true' }}
      run: npm install --no-audit --no-fund
      shell: bash
